### ISSUE TITLE
Deploy to Heroku...

### ISSUE THREAD

**Issue by felipesere** [felipesere/advisorex#33]
Maaaybe get a custom domain?
Maaaaybe under something-something.8thlight.com?

Make sure it's 100% repeatable AND it works from Travis-CI.

Note: What do we do with the migrations? Should they run automagically? What about rolling back once?

**Comment by fabientownsend** [comment]
Something I thought for Lunchbot

Local
|> Build with Travis for the Unit Test and Integration Test
|> Acceptance/Pre-prod was a specific Heroku's instance (the tests were manual here)
|> Production was another Heroku's instance

Heroku can be triggered whenever you merge on the master or any other branch which could be really cool for a continuous delivery.

For the rolling back, aside take the habit of writing **tag**, is there any other alternative?
