### ISSUE TITLE
Improve the CSS maintenance...

### ISSUE THREAD

**Issue by felipesere** [felipesere/advisorex#40]

**Comment by fabientownsend** [comment]
What do you mean by that? Use something like Sass?

**Comment by felipesere** [comment]
Maybe 😀 There is no framework or consistent naming scheme. I don't even know what the most user friendly setup is at the moment...

**Comment by fabientownsend** [comment]
My CSS skill is a bit rusty. There is this kind of _naming scheme_ which can be helpful: [BEM](http://getbem.com/introduction/)
