### ISSUE TITLE
Image not displaying on dashboard

### ISSUE THREAD

**Issue by onlyskin** [felipesere/advisorex#86]
I pasted a URL to my github image, when I navigate away and back, my dashboard has remembered the URL I gave it but does not display any image.
![screen shot 2017-11-30 at 13 18 38](https://user-images.githubusercontent.com/3614633/33428392-45fe4d7e-d5d1-11e7-979f-2291c98203b3.png)

**Comment by felipesere** [comment]
See #87  😸

**Comment by felipesere** [comment]
Done!
